# Generated by Django 4.1.7 on 2023-03-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('maximum_temperature', models.IntegerField()),
                ('minimum_temperature', models.IntegerField()),
                ('amount_of_precipitation', models.IntegerField()),
            ],
            options={
                'unique_together': {('station_id', 'date')},
            },
        ),
    ]
