# Generated by Django 4.1.7 on 2023-03-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=11)),
                ('year', models.CharField(max_length=4)),
                ('average_maximum_temperature', models.FloatField()),
                ('average_minimum_temperature', models.FloatField()),
                ('average_amount_of_precipitation', models.FloatField(help_text='Unit in cm')),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='amount_of_precipitation',
            field=models.IntegerField(help_text='Unit in mm'),
        ),
    ]
